### POST Request to add a Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Some name344546",
    "email": "admin3bebe41@gmail.com",
    "address": "Some address34verfe",
    "dateOfBirth": "1995-04-06",
    "registeredDate": "1995-04-06"
}

###