### POST Request to add a Patient
POST http://lb-af9ff481.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Nkosi Mkhize 2",
  "email": "nkosi.mkhize2@gmail.com",
  "address": "Los Angelas2",
  "dateOfBirth": "1992-02-06",
  "registeredDate": "1995-02-16"
}

###