### POST Request to add a Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Some name",
    "email": "admin@gmail.com",
    "address": "Some address",
    "dateOfBirth": "1995-04-06",
    "registeredDate": "1995-04-06"
}

###