### PUT requests to update patient details
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Name 2",
  "email": "john.doe@example.com",
  "address": "New address",
  "dateOfBirth": "1994-02-04",
  "registeredDate": "2025-05-01"
}
###