name: Build Auth Service

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    uses: ./.github/workflows/java-maven-build.yml
    with:
      service_name: auth-service
      build_type: docker
      dockerfile_path: auth-service/Dockerfile
      java_version: 21
      java_distribution: temurin
      skip_tests: false
      maven-version: 3.9.9
