name: Build Microservice Project (Reusable)

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '21'
      maven-version:
        required: false
        type: string
        default: '3.9.9'
      java_distribution:
        required: false
        type: string
        default: 'temurin'
      skip_tests:
        required: false
        type: boolean
        default: false
      build_type:
        required: false
        type: string
        default: 'docker' # options: docker, maven-jkube
      dockerfile_path:
        required: false
        type: string
        default: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Git short SHA
        id: tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java_distribution }}
          java-version: ${{ inputs.java_version }}

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: ${{ inputs.maven-version }}

      - name: Build with Maven
        run: |
          if ${{ inputs.skip_tests }}; then
            mvn clean install -DskipTests
          else
            mvn clean install
          fi

      - name: Docker Build
        if: ${{ inputs.build_type == 'docker' }}
        env:
          IMAGE_TAG: ${{ steps.tag.outputs.tag }}
        run: |
          docker build -t ${{ inputs.service_name }}$IMAGE_TAG -f ${{ inputs.dockerfile_path }} .